name: Deploy para Hostnet via SFTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c칩digo
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}       # Usando o segredo do host
          port: 22
          user: ${{ secrets.SFTP_USER }}       # Usando o segredo do usu치rio
          pass: ${{ secrets.SFTP_PASS }}       # Usando o segredo da senha
          localDir: './'                       # Diret칩rio local
          remoteDir: '/public_html'            # Diret칩rio remoto
          options: '--reverse --delete --verbose'
