name: Deploy para Hostnet via SFTP

on:
  push:
    branches:
      - main  # Ou outro branch principal que você estiver usando

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Deploy via SFTP
        uses: pressidium/lftp-mirror-action@v1
        with:
          host: ${{ secrets.SFTP_HOST }}
          port: 22
          user: ${{ secrets.SFTP_USER }}
          pass: ${{ secrets.SFTP_PASS }}  # Alterado de "password" para "pass"
          localDir: './'             # Altere se quiser subir só uma pasta específica (ex: ./dist)
          remoteDir: '/public_html'  # Altere conforme o caminho do seu site no servidor
          options: '--reverse --delete --verbose'
